# OpenShift OAuth Configuration - Manual OAuth Client Approach
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-auth-proxy-config
  namespace: default
data:
  # OpenShift OAuth Provider
  provider: "openshift"
  
  # OAuth Client ID - must match the OAuthClient resource name exactly
  client-id: "kube-auth-proxy"
  
  # Proxy Settings
  http-address: "0.0.0.0:4180"
  upstreams: "http://example-app:8080"
  
  # Email domains (configure as needed)
  email-domains: "*"
  
  # Redirect URI - replace with your actual domain
  redirect-url: "https://your-app.apps.cluster.example.com/oauth2/callback"
  
  # OpenShift OAuth scope
  scope: "user:info"
  
  # Header forwarding
  pass-basic-auth: "false"
  pass-access-token: "true"
  pass-user-headers: "true"
  pass-host-header: "true"
  
  # Session settings
  cookie-expire: "1h"
  cookie-refresh: "30m"
  
  # TLS Configuration - uses automatic service account CA
  use-system-trust-store: "true"

---
apiVersion: v1
kind: Secret
metadata:
  name: kube-auth-proxy-secret
  namespace: default
type: Opaque
stringData:
  # Must match the secret in the OAuthClient resource
  client-secret: "REPLACE-WITH-BASE64-ENCODED-SECRET"
  
  # Generate a random 32-byte base64-encoded string for cookie encryption
  # Example: openssl rand -base64 32
  cookie-secret: "REPLACE-WITH-BASE64-ENCODED-32-BYTE-SECRET"
