# OIDC Configuration for kube-auth-proxy
# Replace placeholder values with your actual OIDC provider details

apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-auth-proxy-config
  namespace: default
data:
  # OIDC Provider Configuration
  provider: "oidc"
  
  # OIDC Provider URLs - replace with your provider's URLs
  oidc-issuer-url: "https://your-oidc-provider.example.com/realms/your-realm"
  
  # Client Configuration - replace with your client ID
  client-id: "your-client-id"
  
  # OAuth2 Scopes
  scope: "openid email profile"
  
  # Proxy Settings
  http-address: "0.0.0.0:4180"
  upstreams: "http://example-app:8080"
  
  # Email domains (configure as needed)
  email-domains: "*"
  
  # Redirect URI configuration - replace with your domain
  redirect-url: "https://your-app.example.com/oauth2/callback"
  
  # OIDC Token Claims
  oidc-groups-claim: "groups"
  oidc-email-claim: "email"
  
  # Header forwarding
  pass-basic-auth: "false"
  pass-access-token: "true"
  pass-user-headers: "true"
  pass-host-header: "true"

---
apiVersion: v1
kind: Secret
metadata:
  name: kube-auth-proxy-secret
  namespace: default
type: Opaque
stringData:
  # Replace with your actual client secret
  client-secret: "your-client-secret"
  
  # Generate a random 32-byte base64-encoded string for cookie encryption
  # Example: openssl rand -base64 32
  cookie-secret: "REPLACE-WITH-BASE64-ENCODED-SECRET"
